version: "3"

networks:
  laravel:
    driver: bridge

volumes:
  vendor:

services:

  php:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - ../src:/var/www/html:rw
      - ./configs/laravel.dev.env:/var/www/html/.env
      - vendor:/var/www/html/vendor
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html:rw
    depends_on:
      - php
    networks:
      - laravel
  
  mysql-db:
    image: mysql
    # This linux/amd64 used for mac M1
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysqla
      - ./configs/dump/:/docker-entrypoint-initdb.d/
    tty: true
    ports:
      - "3306:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    # This linux/amd64 used for mac M1
    platform: linux/amd64
    restart: always
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    volumes:
      - ./configs/pma.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    networks:
      - laravel

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - laravel
  


